### ISSUE TITLE
Static Assets

### ISSUE THREAD

**Issue by snowman-repos** [topheman/webpack-babel-starter#3]
I'm using this as a learning tool to try putting together a simple webpage. Not necessarily related to your starter kit specifically, but I was wondering how one might deal with things like robots.txt that you might want to just copy over to the build directory? It wouldn't make sense to require these kind of static assets somewhere in the html/css/js. I'm also struggling to get favicons to appear in the build directory.

```javascript
{ test: /\.(png|jpg|jpeg|webp|ico)$/, loader: 'url-loader?limit=' + ASSETS_LIMIT + '&name=assets/[hash].[ext]' },
```

```html
<link rel="shortcut icon" href="<%= require('./assets/icons/favicon.ico') %>" type="image/ico">
```

**Comment by topheman** [comment]
1) About `robots.txt`

I have never really thought about this. Since this file isn't "part of your app" (only crawlers will access it), it might not need to be a part of the webpack flow

You could simply add `cp ./src/robots.txt ./build/dist` in a `postbuild-prod` task (there are ways to make it even more generic).

If you want webpack to be in charge of this part, you use [copy-webpack-plugin](https://github.com/kevlened/copy-webpack-plugin).

2) For the favicon

Try to add this loader:

```
{ test: /\.(ico)$/, loader: 'file-loader?name=assets/[hash].[ext]' },
```

Please tell me how it worked for you, I might add those features to this project ...

**Comment by snowman-repos** [comment]
Duh, why didn't I think of that. Thanks, both solutions work perfectly!
